export interface ManufacturingItemI {
  ITEM_M_ID: number
  ITEM_ID: number
  ITEM_CATEGORY_ALPHABET: string
  ITEM_CATEGORY_ID: number
  ITEM_CATEGORY_NAME: string
  ITEM_CODE_FOR_SUPPORT_MES: string
  ITEM_EXTERNAL_CODE: string
  ITEM_EXTERNAL_FULL_NAME: string
  ITEM_EXTERNAL_SHORT_NAME: string
  ITEM_INTERNAL_CODE: string
  ITEM_INTERNAL_FULL_NAME: string
  ITEM_INTERNAL_SHORT_NAME: string
  ITEM_PROPERTY_COLOR_ID: number
  ITEM_PROPERTY_COLOR_NAME: string
  ITEM_PROPERTY_SHAPE_ID: number
  ITEM_PROPERTY_SHAPE_NAME: string
  ITEM_PURPOSE_ID: number
  ITEM_PURPOSE_NAME: string
  COLOR_ID: number
  COLOR_HEX: string
  COLOR_NAME: string
  MAKER_ID: number
  MAKER_NAME: string
  VENDOR_ALPHABET: string
  VENDOR_ID: number
  PURCHASE_UNIT_ID: number
  PURCHASE_UNIT_RATIO: number
  PURCHASE_UNIT_SYMBOL: string
  USAGE_UNIT_ID: number
  USAGE_UNIT_RATIO: number
  USAGE_UNIT_SYMBOL: string
  LEAD_TIME: number
  MOQ: number
  SAFETY_STOCK: number
  No: number
  UPDATE_BY: string
  UPDATE_DATE: string
  INUSE: number
  INUSE_RAW_DATA: number
  PURCHASE_MODULE_ID: number
}
