export interface ProductTypeI {
  PRODUCT_TYPE_ID: number
  // PRODUCT_CATEGORY_ID: number;
  PRODUCT_TYPE_CODE: string
  PRODUCT_TYPE_NAME: string
  PRODUCT_TYPE_ALPHABET: string
  SUFFIX_FOR_PART_NUMBER: string
  PRODUCT_SPECIFICATION_DOCUMENT_SETTING_NAME: string
  PRODUCT_SPECIFICATION_DOCUMENT_SETTING_NUMBER: string
  PRODUCT_SPECIFICATION_DOCUMENT_SETTING_VERSION_REVISION: string
  IS_PRODUCT_FOR_REPAIR: string
  IS_PRODUCT_LEVEL_FOR_GEN_PRODUCT_TYPE_CODE: string
  PRODUCT_CATEGORY_ID: number
  PRODUCT_CATEGORY_ALPHABET: string
  PRODUCT_CATEGORY_CODE: string
  PRODUCT_MAIN_ID: number
  PRODUCT_MAIN_ALPHABET: string
  PRODUCT_SUB_ID: number
  PRODUCT_SUB_ALPHABET: string
  ITEM_CATEGORY_ID: number
  FLOW_ID: number
  FLOW_CODE: number
  BOM_ID: number
  BOM_CODE: string
  BOI_PROJECT_NAME: string
  BOI_PROJECT_CODE: string
  ACCOUNT_DEPARTMENT_CODE_ID: number
  ACCOUNT_DEPARTMENT_CODE: string
  PC_NAME: string
  PRODUCT_ITEM_NAME: string
  PRODUCT_ITEM_CODE: string
  IS_FFT_PART_NUMBER: string
  IS_BOI: string
  PRODUCT_TYPE_STATUS_WORKING_ID: number
  PRODUCT_TYPE_PROGRESS_WORKING_ID: number

  CREATE_BY: string
  CREATE_DATE: string
  UPDATE_BY: string
  UPDATE_DATE: string
  DESCRIPTION: string
  INUSE: string // 0 , 1

  // ------
  PRODUCT_ITEM_ID: number
  PRODUCT_CATEGORY_NAME: string
  PRODUCT_MAIN_NAME: string
  PRODUCT_SUB_NAME: string
  BOM_NAME: string
  FLOW_NAME: string

  PRODUCT_SPECIFICATION_TYPE_ID: number
  PRODUCT_SPECIFICATION_TYPE_ALPHABET: string
  PRODUCT_SPECIFICATION_TYPE_NAME: string

  P2_NEED: number
  P2_START_MONTH_NO: number
  P3_START_MONTH_NO: number
}
