export interface SctDetailForAdjustI {
  TOTAL_INDIRECT_COST: number
  CIT: number
  VAT: number
  GA: number
  MARGIN: number
  SELLING_EXPENSE: number
  ADJUST_PRICE: number
  REMARK_FOR_ADJUST_PRICE: string
  IS_FROM_SCT_COPY: number

  TOTAL_INDIRECT_COST_SCT_RESOURCE_OPTION_ID: number
  CIT_SCT_RESOURCE_OPTION_ID: number
  VAT_SCT_RESOURCE_OPTION_ID: number
  GA_SCT_RESOURCE_OPTION_ID: number
  MARGIN_SCT_RESOURCE_OPTION_ID: number
  SELLING_EXPENSE_SCT_RESOURCE_OPTION_ID: number
  ADJUST_PRICE_SCT_RESOURCE_OPTION_ID: number
}
